# Base image with Node.js
FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Install global dependencies
RUN npm install -g typescript ts-node

# Copy application source code
COPY . .

# Build Typescript files
RUN npm run build

# Expose port
EXPOSE 9000

# Start the application (run compiled JS file)
CMD ["node", "dist/server.js"]
